[package]
name = "mandolin-cards-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
genanki-rs = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4.0", features = ["derive"] }
